/** Multilingual labels for pre-order / booking UI */
const labels: Record<string, Record<string, string>> = {
  en: {
    menu: 'Menu',
    items: 'items',
    item: 'item',
    voiceGuide: '🎧 Voice Guide',
    stopNarration: 'Stop Narration',
    readAloud: 'Read Aloud',
    preOrder: 'Pre-order',
    checkout: 'Check Out',
    totalItems: 'items selected',
    booking: 'Booking Details',
    fullName: 'Full Name',
    fullNamePlaceholder: 'e.g. John Doe',
    arrivalTime: 'Arrival Time',
    people: 'People',
    note: 'Note (optional)',
    notePlaceholder: 'Allergies, special requests…',
    submit: 'Confirm Order',
    submitting: 'Submitting…',
    successTitle: 'Order Placed! 🎉',
    successMessage: "We'll prepare your dishes. See you soon!",
    close: 'Done',
    open: '✅ Open',
    closed: '🚫 Closed',
  },
  vi: {
    menu: 'Thực đơn',
    items: 'món',
    item: 'món',
    voiceGuide: '🎧 Hướng dẫn giọng nói',
    stopNarration: 'Dừng đọc',
    readAloud: 'Đọc to',
    preOrder: 'Đặt trước',
    checkout: 'Thanh toán',
    totalItems: 'món đã chọn',
    booking: 'Thông tin đặt bàn',
    fullName: 'Họ và tên',
    fullNamePlaceholder: 'VD: Nguyễn Văn A',
    arrivalTime: 'Giờ đến',
    people: 'Số người',
    note: 'Ghi chú (tùy chọn)',
    notePlaceholder: 'Dị ứng, yêu cầu đặc biệt…',
    submit: 'Xác nhận đơn',
    submitting: 'Đang gửi…',
    successTitle: 'Đặt thành công! 🎉',
    successMessage: 'Chúng tôi sẽ chuẩn bị món. Hẹn gặp bạn!',
    close: 'Xong',
    open: '✅ Mở cửa',
    closed: '🚫 Đóng cửa',
  },
};

export function t(lang: string, key: string): string {
  return labels[lang]?.[key] ?? labels.en[key] ?? key;
}
