/** Multilingual labels for pre-order / booking UI */
const labels: Record<string, Record<string, string>> = {
  en: {
    menu: 'Menu',
    items: 'items',
    item: 'item',
    voiceGuide: '🎧 Voice Guide',
    stopNarration: 'Stop Narration',
    readAloud: 'Read Aloud',
    close: 'Done',
    open: '✅ Open',
    closed: '🚫 Closed',
    // ─── Smart Menu labels ───────────────────────────
    smartMenu: 'Smart Menu',
    filterDietary: 'Filter by Dietary',
    allItems: 'All',
    recommended: '⭐ Recommended',
    originalName: 'Vietnamese Name',
    noMenuItems: 'No menu items available.',
    noMatchFilters: 'No items match your dietary filters.',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    glutenFree: 'Gluten-free',
    peanutFree: 'Peanut-free',
    seafood: 'Seafood',
    spicy: 'Spicy',
    dairyFree: 'Dairy-free',
    price: 'Price',
    // ─── Combo / Set Menu labels ─────────────────────
    comboSection: 'Value Set Menus',
    valueDeal: '💎 Value Deal',
    includes: 'Includes',
    addToBill: '+ Add to Bill',
    added: '✓ Added',
    // ─── Visual Communication Bill ───────────────────
    viewBill: 'View Bill',
    communicationBill: 'Your Order',
    billSubtitle: 'Show this screen to the waiter',
    totalVnd: 'Total (VND)',
    totalConverted: 'Approx.',
    clearBill: 'Clear Bill',
    closeBill: 'Close',
    emptyBill: 'Your bill is empty.',
    emptyBillHint: 'Add dishes or combos from the menu!',
    qty: 'qty',
  },
  vi: {
    menu: 'Thực đơn',
    items: 'món',
    item: 'món',
    voiceGuide: '🎧 Hướng dẫn giọng nói',
    stopNarration: 'Dừng đọc',
    readAloud: 'Đọc to',
    close: 'Xong',
    open: '✅ Mở cửa',
    closed: '🚫 Đóng cửa',
    // ─── Smart Menu labels ───────────────────────────
    smartMenu: 'Thực đơn thông minh',
    filterDietary: 'Lọc theo chế độ ăn',
    allItems: 'Tất cả',
    recommended: '⭐ Đề xuất',
    originalName: 'Tên tiếng Việt',
    noMenuItems: 'Chưa có món ăn.',
    noMatchFilters: 'Không có món nào phù hợp.',
    vegetarian: 'Chay',
    vegan: 'Thuần chay',
    glutenFree: 'Không gluten',
    peanutFree: 'Không đậu phộng',
    seafood: 'Hải sản',
    spicy: 'Cay',
    dairyFree: 'Không sữa',
    price: 'Giá',
    // ─── Combo / Set Menu labels ─────────────────────
    comboSection: 'Combo tiết kiệm',
    valueDeal: '💎 Tiết kiệm',
    includes: 'Bao gồm',
    addToBill: '+ Thêm',
    added: '✓ Đã thêm',
    // ─── Visual Communication Bill ───────────────────
    viewBill: 'Xem hóa đơn',
    communicationBill: 'Đơn hàng',
    billSubtitle: 'Cho nhân viên xem màn hình này',
    totalVnd: 'Tổng (VND)',
    totalConverted: 'Khoảng',
    clearBill: 'Xóa đơn',
    closeBill: 'Đóng',
    emptyBill: 'Đơn hàng trống.',
    emptyBillHint: 'Thêm món từ thực đơn!',
    qty: 'SL',
  },
};

export function t(lang: string, key: string): string {
  return labels[lang]?.[key] ?? labels.en[key] ?? key;
}
